--- a/usr.bin/smbutil/Makefile
+++ b/usr.bin/smbutil/Makefile
@@ -6,6 +6,8 @@
 DPADD=	${LIBSMB} ${LIBKICONV}
 LDADD=	-lsmb -lkiconv
 
+LDADD+=	-L../../lib/libsmb
+
 CONTRIBDIR=	${.CURDIR}/../../contrib/smbfs
 CFLAGS+=	-I${CONTRIBDIR}/include
 
--- a/usr.sbin/mount_smbfs/Makefile
+++ b/usr.sbin/mount_smbfs/Makefile
@@ -11,6 +11,8 @@
 LDADD=	-lsmb -lkiconv
 DPADD=	${LIBSMB} ${LIBKICONV}
 
+LDADD+=	-L../../lib/libsmb
+
 .PATH:	${CONTRIBDIR}/mount_smbfs
 .PATH:  ${MOUNTDIR}
 
